version: '2'
services:
    research_mgr-app:
        image: research_mgr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://research_mgr-postgresql:5432/research_mgr
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    research_mgr-postgresql:
        extends:
            file: postgresql.yml
            service: research_mgr-postgresql
